[package]
name = "bof_cli"
version = "0.1.0"
authors = ["Deathlesz"]
edition = "2021"
description = "A CLI for BOF archiver."
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
bof = { path = "../bof" }
clap = "4.5"
